version: "2"
services:
  master_db:
    build: mysql/master
    container_name: master-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33061:3306
    volumes:
      - ./volume/master:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    env_file:
      - .env
  slave_db:
    build: mysql/slave
    container_name: slave-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33062:3306
    volumes:
      - ./volume/slave:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8085